### PR TITLE
Display Assignee of the issue on BountyCardDetails component

### PR DESCRIPTION
**Pull request by jhonnyV-V**
this should meet the conditions of #337, and as feedback adding some mocked bounties could make easy the development for the developers that are not part of the core team :)

### CODE REVIEW

**Comment by jhonnyV-V** [comment]
Closes #337

**Comment by FlacoJones** [comment]
Hey @jhonnyV-V thank you for the PR! I'll review this ASAP so you can secure https://app.openq.dev/bounty/0xbea6ffc0a6759e5d8171a4f6a6787038e4f4b7e6

**Review by Christopher-Stevers — CHANGES_REQUESTED** [review]
In general it looks good! Just a couple of changes to request. 
In the CopyBountyAssigneeLink component could make assignment of a value to `const assignee` conditional? Right now the page breaks while its waiting to load a bounty. 
Then, in GithubRepository.js there is a parseIssueData that processes the queried data.
add assignees to the return object there. 
To do that you'd want something like this.
```
		const assignees = responseData.assignees.nodes;
		return { assignees, id, title, body, url, repoName, owner, avatarUrl, labels, createdAt, closed, bodyHTML, titleHTML, twitterUsername, number };```
	I imagine dealing with the data fetching is a bit of when you are just deving on the frontend end repo.
	Thanks for the contribution @jhonnyV-V  and just wait on @FlacoJones '  review before implementing changes.

**Comment by FlacoJones** [comment]
Re-merge development into this branch, as some PRs went in ahead of it

**Comment by jhonnyV-V** [comment]
> In general it looks good! Just a couple of changes to request. In the CopyBountyAssigneeLink component could make assignment of a value to `const assignee` conditional? Right now the page breaks while its waiting to load a bounty. Then, in GithubRepository.js there is a parseIssueData that processes the queried data. add assignees to the return object there. To do that you'd want something like this.
> 
> ```
> 		const assignees = responseData.assignees.nodes;
> 		return { assignees, id, title, body, url, repoName, owner, avatarUrl, labels, createdAt, closed, bodyHTML, titleHTML, twitterUsername, number };```
> 	I imagine dealing with the data fetching is a bit of when you are just deving on the frontend end repo.
> 	Thanks for the contribution @jhonnyV-V  and just wait on @FlacoJones '  review before implementing changes.
> ```

I just implemented the changes, in this moment CopyBountyAssigneeLink should not be displayed if theres no bounty loaded, since if the assignee field does not exist once the bounty is loaded the Skeleton component will be displayed, so at the moment I think that could be better to simply hide it if there's no bounty loaded or no assignee field

**Review by Christopher-Stevers — APPROVED** [review]

**Review by Christopher-Stevers — APPROVED** [review]

**Review by FlacoJones — APPROVED** [review]

**Pull request merged**
