### PR TITLE
Design Github profile page

### PR DESCRIPTION
**Pull request by ArcAnya**
Update Github Profile page design:

image

### CODE REVIEW

**Comment by Christopher-Stevers** [comment]
Just one note - someone probably missed this in an earlier review, please don't change artifact names, as it can lead to confusion where we think we have the right abi on the FE, but its actually an out of date that's been renamed. If you need a different name, just change where its called from, that way its easier to find the issue when debugging.

**Comment by ArcAnya** [comment]
What's an artifact name exactly, i.e. which part should I have done differently?
Thanks for the feedback <3

**Comment by Christopher-Stevers** [comment]
Artifacts are a folder than contain the abis, they're copy pasted from contracts. Here they are in the FE file system:
image

**Comment by Christopher-Stevers** [comment]
Then updated at the top of openQClient.
image
So whenever there is a contract update, you need to copy new ones from contracts (they show up as artifacts there as well).
I'm guessing you changed the name of the file, because the name of the import was updated but not the file for you or something. Not sure though, it could have been on my end. In any case, if you ever have an artifact not found, either update the contracts or change the name of the import because it gets confusing when the filename is changed.

**Comment by ArcAnya** [comment]
Ah ok, yes indeed, I had changed both the path name and the filename - I'm having the same issue now on staging, so I'm guessing I only change the pathname like so - or would it be best to copy the full folder "implementations" from the contracts into the FE?

image

**Comment by Christopher-Stevers** [comment]
yeah, just change the file name, . . we'll wait till hackathons are merged into staging to copy the whole file.

**Pull request merged**
