### PR TITLE
unstoppable domain login integration

### LINKED ISSUE #1193: [FIXED PRICE CONTRACT]: add Login with Unstoppable for the OpenQ website.
### 📃 Description

This issue will be funded with a grant from Unstoppable Domains

### 👨‍⚖️ Acceptance Criteria

1. The UI looks like the mockup example
2. Wallet connection is fully functional with similar performance as the connect with MetaMask option
3. Current network is Polygon, but we should allow it to scale in the future

### 💰 Budget

500 USDC

### 🗓 Timeline/Deadline

_No response_

### 🖼 Screenshots + Mock Ups

image

### 🎬 Where to Start

See the dev docs from Unstoppable Domains for more information: 
https://docs.unstoppabledomains.com/login-with-unstoppable/

### 📵 What's Out of Scope

_No response_

### 🤳 User Story

1. After user registers / login
2. The user wants to connect their wallet by clicking on connect wallet
3. They should get multiple options to connect, amongst which, Login with Unstoppable (see Mock up)
4. Click login with Unstoppable 
5. Go through the authentication flow with Unstoppable 
6. Login with Polygon (only network currently active

### 👩‍💻 Developer Story

_No response_

### 🛠 Tools to Use

_No response_

### 🖇 Resources

_No response_

### PR DESCRIPTION
**Pull request by ManyRios**
Closes https://github.com/OpenQDev/OpenQ-Frontend/issues/1193  Adding Unstoppable Domain login Integration

### CODE REVIEW

**Comment by ManyRios** [comment]
Hey, I need a feedback about this @BowTiedHeron  🙂

**Comment by BowTiedHeron** [comment]
> Hey, I need a feedback about this @BowTiedHeron 🙂

you mind running a linter/prettier and updating your branch with the latest changes?
its hard to compare this way what has been added.

**Comment by ManyRios** [comment]
> > Hey, I need a feedback about this @BowTiedHeron 🙂
> 
> you mind running a linter/prettier and updating your branch with the latest changes? its hard to compare this way what has been added.

always run eslint --fix 

Screenshot_4

**Comment by ManyRios** [comment]
Any update?

**Pull request closed without merging**
